spring:
  datasource:
    url: jdbc:mysql://10.0.0.3/mydb
    username: root
    password: Reflexis@123
    driverClassName: com.mysql.jdbc.Driver
    iptypes: PRIVATE
    socketFactory: com.google.cloud.sql.mysql.SocketFactory
    cloudSqlInstance:   loyal-flames-365105:us-central1-c:employee-db
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.MySQL5Dialect
  h2:
    console.enabled: true
    console:
      settings:
        web-allow-others: true