spring:
  datasource:
    url: jdbc:mysql://34.72.73.212/mydb
    username: root
    password: Reflexis@123
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.MySQL5Dialect
  h2:
    console.enabled: true
    console:
      settings:
        web-allow-others: true